"""
backfill_snapshots.py
─────────────────────────────────────────────────────────────
One-shot dataset upgrade: walks every existing trajectory row
in `sft_data/expert_trajectories.jsonl` through a fresh
IncidentEnvironment and attaches the `env_snapshot` field that
GRPO needs at line 171 of `agent/train_grpo.py`.

Why this script exists:
    The committed JSONL was generated by an earlier version of
    `agent/generate_sft_data.py` that didn't yet save snapshots.
    Without snapshots, `evaluate_single_env` falls back to
    `env.reset(task_id=tid)` and grades every commander action
    against the step-1 fresh state — making the RL signal random.

Why we replay instead of regenerating:
    Regenerating from scratch costs ~4000 teacher API calls and
    risks degrading response quality if the new teacher is weaker.
    Replay preserves every teacher response verbatim.

Approach:
    1. Read all rows; sort into episodes by (task_id, step) order.
       Episode boundary = step number resets to 1.
    2. For each episode: env.reset(task_id), then for each
       (scout, commander) pair at step S: save_snapshot BEFORE
       executing, attach to both rows, parse the commander's
       action JSON, env.step(action).
    3. Write back atomically; old file is moved to .bak.

Run:
    python scripts/backfill_snapshots.py
"""

import json
import re
import sys
import shutil
from pathlib import Path
from collections import defaultdict

sys.stdout.reconfigure(encoding="utf-8")

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from incident_env.server.incident_environment import IncidentEnvironment
from incident_env.models import IncidentAction


SFT_PATH = REPO_ROOT / "sft_data" / "expert_trajectories.jsonl"
BAK_PATH = SFT_PATH.with_suffix(".jsonl.bak")


def parse_action(response: str) -> dict:
    """Mirror generate_sft_data.ExpertEpisodeRunner._parse_action."""
    match = re.search(r"<action>(.*?)</action>", response, re.DOTALL)
    text = match.group(1).strip() if match else response

    if "```" in text:
        parts = text.split("```")
        if len(parts) >= 2:
            code = parts[1]
            if code.startswith("json"):
                code = code[4:]
            text = code.strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        brace = re.search(r"\{[^{}]*\}", text)
        if brace:
            try:
                return json.loads(brace.group())
            except json.JSONDecodeError:
                pass
        return {"command": "check_status"}


def main():
    if not SFT_PATH.exists():
        print(f"ERROR: {SFT_PATH} not found")
        sys.exit(1)

    print(f"Loading {SFT_PATH} ...")
    with SFT_PATH.open(encoding="utf-8") as f:
        rows = [json.loads(line) for line in f if line.strip()]
    print(f"  {len(rows)} rows total")

    already_have_snapshot = sum(1 for r in rows if r.get("env_snapshot"))
    print(f"  {already_have_snapshot} rows already have env_snapshot")
    if already_have_snapshot == len(rows):
        print("Nothing to do — every row already has env_snapshot. Exiting.")
        return

    episodes = []
    current = []
    last_step = None
    for r in rows:
        step = r.get("step", 1)
        if last_step is not None and step < last_step:
            episodes.append(current)
            current = []
        current.append(r)
        last_step = step
    if current:
        episodes.append(current)

    print(f"  Detected {len(episodes)} episodes")

    by_task = defaultdict(int)
    for ep in episodes:
        by_task[ep[0].get("task_id", "?")] += 1
    print(f"  Episodes per task: {dict(by_task)}")

    env = IncidentEnvironment()
    upgraded = 0
    skipped_episodes = 0

    for ep_idx, episode in enumerate(episodes, 1):
        task_id = episode[0].get("task_id", "easy")
        try:
            env.reset(task_id=task_id)
        except Exception as exc:
            print(f"  [ep {ep_idx}] reset({task_id}) failed: {exc} — skipping")
            skipped_episodes += 1
            continue

        steps = defaultdict(dict)
        for r in episode:
            steps[r.get("step", 1)][r.get("role")] = r

        for step_num in sorted(steps.keys()):
            pair = steps[step_num]
            try:
                snapshot = env.save_snapshot()
            except Exception as exc:
                print(f"  [ep {ep_idx} step {step_num}] save_snapshot failed: {exc}")
                break

            for role in ("scout", "commander"):
                row = pair.get(role)
                if row is not None:
                    row["env_snapshot"] = snapshot
                    upgraded += 1

            cmdr = pair.get("commander")
            if cmdr is None:
                break

            try:
                action_dict = parse_action(cmdr.get("response", ""))
                action = IncidentAction(
                    command=action_dict.get("command", "check_status"),
                    target=action_dict.get("target") or "",
                    parameters=action_dict.get("parameters", {}),
                )
                result = env.step(action)
                if result.get("done"):
                    break
            except Exception as exc:
                print(f"  [ep {ep_idx} step {step_num}] env.step failed: {exc}")
                break

    print(f"\nUpgraded {upgraded}/{len(rows)} rows with env_snapshot")
    print(f"Skipped {skipped_episodes} episodes due to reset failure")

    phantom_rows = [r for r in rows if not r.get("env_snapshot")]
    if phantom_rows:
        print(
            f"Dropping {len(phantom_rows)} phantom rows the env terminates "
            f"before reaching (env logic likely tightened since teacher data was generated)"
        )
    cleaned = [r for r in rows if r.get("env_snapshot")]
    print(f"Final clean dataset: {len(cleaned)} rows")

    print(f"\nBacking up original -> {BAK_PATH.name}")
    shutil.copy2(SFT_PATH, BAK_PATH)

    tmp = SFT_PATH.with_suffix(".jsonl.tmp")
    with tmp.open("w", encoding="utf-8") as f:
        for r in cleaned:
            f.write(json.dumps(r) + "\n")
    tmp.replace(SFT_PATH)
    print(f"Wrote upgraded JSONL -> {SFT_PATH}")

    with SFT_PATH.open(encoding="utf-8") as f:
        verify = [json.loads(line) for line in f if line.strip()]
    have = sum(1 for r in verify if r.get("env_snapshot"))
    print(f"\nVerification: {have}/{len(verify)} rows have env_snapshot")
    if have == len(verify):
        print("SUCCESS - every row carries a snapshot.")
    else:
        print(f"FAIL - {len(verify) - have} rows still missing snapshot")
        sys.exit(2)


if __name__ == "__main__":
    main()
