"""
Cold-Start Supervised Fine-Tuning (SFT)
=======================================
Phase 1 of the DeepSeek R1 Training Recipe.

Before jumping into GRPO (RL), we must teach the small 1.5B model the 
correct OUTPUT FORMAT and domain vocabulary. If we skip this, the model
will suffer from "entropy collapse" during RL and fail to converge.

This script takes the expert CoT trajectories generated by `generate_sft_data.py`
and trains the model using QLoRA.
"""

import os
import sys
import argparse
from typing import Dict, Any

from datasets import load_dataset
from trl import SFTTrainer, SFTConfig
from transformers import TrainingArguments

try:
    from unsloth import FastLanguageModel, is_bfloat16_supported
except ImportError:
    print("Please install unsloth: pip install unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git")
    sys.exit(1)


def main():
    parser = argparse.ArgumentParser(description="Cold-Start SFT Training")
    parser.add_argument("--data", default="sft_data/expert_trajectories.jsonl", help="Path to jsonl trajectories")
    parser.add_argument("--model", default="deepseek-ai/DeepSeek-R1-Distill-Qwen-32B", help="Base model")
    parser.add_argument("--output", default="models/sft_checkpoint", help="Output directory")
    args = parser.parse_args()

    print(f"\n{'='*60}")
    print(f"  STAGE 1: COLD-START SUPERVISED FINE-TUNING")
    print(f"{'='*60}\n")

    # 1. Load Model with Unsloth Optimizations (4-bit QLoRA)
    print("Loading model and tokenizer...")
    max_seq_length = 2048 # SFT needs longer context to read full episodes
    
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=args.model,
        max_seq_length=max_seq_length,
        dtype=None, # Auto-detect
        load_in_4bit=True,
    )

    # 2. Attach PEFT (LoRA) Adapters
    print("Attaching LoRA adapters...")
    model = FastLanguageModel.get_peft_model(
        model,
        r=16, # Rank 16 is fine for SFT format teaching
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", 
                        "gate_proj", "up_proj", "down_proj"],
        lora_alpha=16,
        lora_dropout=0,
        bias="none",
        use_gradient_checkpointing="unsloth", # Highly optimized mapping
        random_state=3407,
    )

    # 3. Load and Format Dataset
    print(f"Loading dataset: {args.data}")
    dataset = load_dataset("json", data_files=args.data, split="train")

    def formatting_prompts_func(example: Dict[str, Any]) -> Dict[str, list]:
        """Convert the jsonl row into the model's required chat format string."""
        formatted_texts = []
        for sys_msg, usr_msg, response in zip(
            example["system_prompt"], 
            example["user_prompt"], 
            example["response"]
        ):
            # We use the tokenizer's chat template directly
            messages = [
                {"role": "system", "content": sys_msg},
                {"role": "user", "content": usr_msg},
                {"role": "assistant", "content": response}
            ]
            text = tokenizer.apply_chat_template(
                messages, 
                tokenize=False, 
                add_generation_prompt=False
            )
            formatted_texts.append(text)
        return {"text": formatted_texts}

    dataset = dataset.map(formatting_prompts_func, batched=True)

    # 4. Training Configuration
    # We use a very low learning rate because we are just teaching format,
    # not trying to rewrite the model's underlying knowledge.
    training_args = SFTConfig(
        per_device_train_batch_size=2, # Tiny batch to save VRAM
        gradient_accumulation_steps=4, # Effective batch = 8
        warmup_steps=10,
        max_steps=200,                # Just enough for cold start
        learning_rate=2e-5,
        fp16=not is_bfloat16_supported(),
        bf16=is_bfloat16_supported(),
        logging_steps=10,
        output_dir=args.output,
        optim="adamw_8bit",           # Saves ~0.5GB VRAM
        dataset_text_field="text",
        max_seq_length=max_seq_length,
    )

    # 5. Execute Training
    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        args=training_args,
    )
    
    print("\nStarting SFT training...")
    trainer.train()

    # 6. Save Artifacts
    print(f"\nSaving model to {args.output}")
    model.save_pretrained(args.output)
    tokenizer.save_pretrained(args.output)
    
    print("Done! The model is now ready for Stage 2: GRPO.")

if __name__ == "__main__":
    main()
