"""
Cold-Start Supervised Fine-Tuning (SFT)
=======================================
Phase 1 of the DeepSeek R1 Training Recipe.

Before jumping into GRPO (RL), we must teach the 14B model (4-bit QLoRA)
the correct OUTPUT FORMAT and domain vocabulary. If we skip this,
the model will suffer from "entropy collapse" during RL and fail to converge.

This script takes the expert CoT trajectories generated by `generate_sft_data.py`
and trains the model using QLoRA.
"""

import sys
import argparse
from typing import Dict, Any

try:
    from unsloth import FastLanguageModel, is_bfloat16_supported # type: ignore
except ImportError:
    print("Please install unsloth: pip install unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git")
    sys.exit(1)

from datasets import load_dataset # type: ignore
from trl import SFTTrainer, SFTConfig # type: ignore


def main():
    parser = argparse.ArgumentParser(description="Cold-Start SFT Training")
    parser.add_argument("--data", default="sft_data/expert_trajectories.jsonl", help="Path to jsonl trajectories")
    # Default: Qwen2.5-14B-Instruct in Unsloth's dynamic 4-bit (~14 GB VRAM).
    # Same chat template family as the original 7B, so existing SFT data and
    # MATPO prompts drop in unchanged. Bigger capacity = deeper causal-chain
    # reasoning on hard scenarios.
    parser.add_argument("--model", default="unsloth/Qwen2.5-14B-Instruct-bnb-4bit", help="Base model")
    parser.add_argument("--output", default="models/sft_checkpoint", help="Output directory")
    args = parser.parse_args()

    print(f"\n{'='*60}")
    print("  STAGE 1: COLD-START SUPERVISED FINE-TUNING")
    print(f"{'='*60}\n")

    # 1. Load Model with Unsloth Optimizations (4-bit QLoRA)
    print("Loading model and tokenizer...")
    max_seq_length = 2048 # SFT needs longer context to read full episodes
    
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=args.model,
        max_seq_length=max_seq_length,
        dtype=None, # Auto-detect
        load_in_4bit=True,
    )

    # 2. Attach PEFT (LoRA) Adapters
    # r=32 (was 16): 14B has more parameters per attention head, so r=32 gives
    # the adapter enough capacity to actually shift behavior on the SFT corpus
    # without leaving the format-teaching signal under-fit.
    print("Attaching LoRA adapters...")
    model = FastLanguageModel.get_peft_model(
        model,
        r=32,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                        "gate_proj", "up_proj", "down_proj"],
        lora_alpha=32,
        lora_dropout=0,
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=3407,
    )

    # 3. Load and Format Dataset
    print(f"Loading dataset: {args.data}")
    dataset = load_dataset("json", data_files=args.data, split="train")

    def formatting_prompts_func(example: Dict[str, Any]) -> Dict[str, list]:
        """Convert the jsonl row into the model's required chat format string."""
        formatted_texts = []
        for sys_msg, usr_msg, response in zip(
            example["system_prompt"], 
            example["user_prompt"], 
            example["response"]
        ):
            # We use the tokenizer's chat template directly
            messages = [
                {"role": "system", "content": sys_msg},
                {"role": "user", "content": usr_msg},
                {"role": "assistant", "content": response}
            ]
            text = tokenizer.apply_chat_template(
                messages, 
                tokenize=False, 
                add_generation_prompt=False
            )
            formatted_texts.append(text)
        return {"text": formatted_texts}

    dataset = dataset.map(formatting_prompts_func, batched=True)

    # 4. Training Configuration
    # We use a very low learning rate because we are just teaching format,
    # not trying to rewrite the model's underlying knowledge.
    training_args = SFTConfig(
        per_device_train_batch_size=2, # Tiny batch to save VRAM
        gradient_accumulation_steps=4, # Effective batch = 8
        warmup_steps=10,
        # 574 examples / 8 effective batch ≈ 72 steps/epoch.
        # 300 steps ≈ 4.2 epochs — enough for the 14B to internalize the
        # MATPO tag format without overfitting the small corpus.
        max_steps=300,
        learning_rate=2e-5,
        fp16=not is_bfloat16_supported(),
        bf16=is_bfloat16_supported(),
        logging_steps=10,
        output_dir=args.output,
        optim="adamw_8bit",           # Saves ~0.5GB VRAM
        dataset_text_field="text",
        max_seq_length=max_seq_length,
    )

    # 5. Execute Training
    # Bug C fix: TRL >= 0.12 renamed `tokenizer` to `processing_class`.
    # Using the new kwarg silences FutureWarnings on 0.12.x and is required
    # on 0.13+ where the legacy alias has been removed.
    trainer = SFTTrainer(
        model=model,
        processing_class=tokenizer,
        train_dataset=dataset,
        args=training_args,
    )
    
    print("\nStarting SFT training...")
    trainer.train()

    # 6. Save Artifacts
    print(f"\nSaving model to {args.output}")
    model.save_pretrained(args.output)
    tokenizer.save_pretrained(args.output)
    
    print("Done! The model is now ready for Stage 2: GRPO.")

if __name__ == "__main__":
    main()
